# Generated by Django 3.1.4 on 2021-06-25 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_user',
            name='user',
        ),
        migrations.AddField(
            model_name='detail_user',
            name='name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detail_user',
            name='certificate_id',
            field=models.CharField(default='V2wZa6A16I', max_length=10),
        ),
    ]
