# Generated by Django 3.1.4 on 2021-06-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210625_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail_user',
            old_name='name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='detail_user',
            name='certificate_id',
            field=models.CharField(default='KkaUiOZzs9', max_length=10),
        ),
    ]
