# Generated by Django 3.1.4 on 2021-07-01 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20210625_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='detail_user',
            name='certificate_id',
            field=models.CharField(default='sBhVM2foSE', max_length=10),
        ),
    ]
