# Generated by Django 3.1.4 on 2021-07-04 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0004_auto_20210701_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_user',
            name='certificate_id',
            field=models.CharField(default='ZyjvOY9FJ0', max_length=10),
        ),
        migrations.AlterField(
            model_name='detail_user',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
