# Generated by Django 3.2.5 on 2021-07-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20210705_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_user',
            name='certificate_id',
            field=models.CharField(default='4tTLuIapBL', max_length=10),
        ),
    ]
