# Generated by Django 3.1.4 on 2021-06-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Z_tech_website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail_user',
        ),
    ]
